name: GuiShop
main: GuiShop\Main
version: 1.0.0-ALPHA1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: PHP-Devs /georgianYT
description: ShopGUI
commands:
 shop:
  description: Opens the shop gui
